// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout_Main from "../../layouts/Layout_Main.mjs";
import * as Component_Title from "../../components/Component_Title.mjs";

function Page_About_View(Props) {
  var user = Props.user;
  var html = Props.html;
  return React.createElement(Layout_Main.make, {
              user: user,
              children: null
            }, React.createElement(Component_Title.make, {
                  text: "About this site",
                  size: "Primary"
                }), React.createElement("div", {
                  className: "prose mb-8",
                  dangerouslySetInnerHTML: {
                    __html: html
                  }
                }));
}

var Title;

var make = Page_About_View;

export {
  Title ,
  make ,
  
}
/* react Not a pure module */
