// Generated by ReScript, PLEASE EDIT WITH CARE


var markdown = "\nThis is an example page demonstrating the use of Markdown for page content.\n\nThis template is based on the [ReScript NextJS Template](https://github.com/ryyppy/rescript-nextjs-template) and the [NextJS MongoDB App](https://github.com/hoangvvo/nextjs-mongodb-app) projects.\n\nThe template includes:\n\n- [ReScript](https://rescript-lang.org) and [ReScript React](https://rescript-lang.org/docs/react/latest/introduction)\n- [NextJS](https://nextjs.org/)\n- [MongoDB](https://www.mongodb.com/)\n- [Tailwind CSS](https://tailwindcss.com/)\n\nIt has simple account features such as signing up, logging in, and basic account management. It also includes [ReCaptcha](https://www.google.com/recaptcha/about/) and account related email notifications using [Send Grid](https://sendgrid.com/).\n\n[View the source code on Github](https://github.com/kevanstannard/rescript-nextjs-mongodb-app)\n";

export {
  markdown ,
  
}
/* No side effect */
