// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import * as Layout_Main from "../../layouts/Layout_Main.mjs";
import * as Component_Form from "../../components/Component_Form.mjs";
import * as Component_Link from "../../components/Component_Link.mjs";
import * as Component_Title from "../../components/Component_Title.mjs";
import * as Component_Button from "../../components/Component_Button.mjs";
import * as Page_Login_Resend from "./Page_Login_Resend.mjs";
import * as Component_AlertMessage from "../../components/Component_AlertMessage.mjs";

function Page_Login_View$LoginError(Props) {
  var error = Props.error;
  var email = Props.email;
  if (error !== undefined) {
    if (error === "LoginFailed") {
      return React.createElement(Component_AlertMessage.make, {
                  type_: "Error",
                  children: "Your email or password is not correct."
                });
    } else if (error === "AccountNotActivated") {
      return React.createElement(Page_Login_Resend.make, {
                  email: email
                });
    } else {
      return React.createElement(Component_AlertMessage.make, {
                  type_: "Error",
                  children: "There was a problem logging you in. Please try again."
                });
    }
  } else {
    return null;
  }
}

var LoginError = {
  make: Page_Login_View$LoginError
};

function Page_Login_View(Props) {
  var email = Props.email;
  var emailError = Props.emailError;
  var password = Props.password;
  var passwordError = Props.passwordError;
  var isSubmitting = Props.isSubmitting;
  var loginError = Props.loginError;
  var onEmailChange = Props.onEmailChange;
  var onPasswordChange = Props.onPasswordChange;
  var onLoginClick = Props.onLoginClick;
  return React.createElement(Layout_Main.make, {
              user: undefined,
              children: null
            }, React.createElement(Component_Form.FormContainer.make, {
                  children: null
                }, React.createElement(Component_Title.make, {
                      text: "Login",
                      size: "Primary"
                    }), React.createElement(Page_Login_View$LoginError, {
                      error: loginError,
                      email: email
                    }), React.createElement(Component_Form.TextField.make, {
                      label: "Email",
                      value: email,
                      onChange: onEmailChange,
                      error: emailError
                    }), React.createElement(Component_Form.PasswordField.make, {
                      label: "Password",
                      value: password,
                      onChange: onPasswordChange,
                      error: passwordError,
                      showPasswordStrength: false
                    }), React.createElement(Component_Button.Button.make, {
                      state: isSubmitting ? "Processing" : "Ready",
                      onClick: onLoginClick,
                      color: "Green",
                      full: true,
                      children: "Login"
                    })), React.createElement("p", {
                  className: "my-4"
                }, React.createElement(Component_Link.make, {
                      href: Common_Url.forgotPassword(undefined),
                      children: "Forgot password?"
                    })));
}

var Main;

var Title;

var AlertMessage;

var Link;

var make = Page_Login_View;

export {
  Main ,
  Title ,
  AlertMessage ,
  Link ,
  LoginError ,
  make ,
  
}
/* react Not a pure module */
