// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Client_User from "../../modules/client/Client_User.mjs";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Router from "next/router";
import * as Page_Login_View from "./Page_Login_View.mjs";

function initialState(param) {
  return {
          email: "",
          password: "",
          isSubmitting: false,
          errors: {
            login: undefined,
            email: undefined,
            password: undefined
          }
        };
}

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* SetEmail */0 :
        return {
                email: action._0,
                password: state.password,
                isSubmitting: state.isSubmitting,
                errors: state.errors
              };
    case /* SetPassword */1 :
        return {
                email: state.email,
                password: action._0,
                isSubmitting: state.isSubmitting,
                errors: state.errors
              };
    case /* SetIsSubmitting */2 :
        return {
                email: state.email,
                password: state.password,
                isSubmitting: action._0,
                errors: state.errors
              };
    case /* SetErrors */3 :
        return {
                email: state.email,
                password: state.password,
                isSubmitting: state.isSubmitting,
                errors: action._0
              };
    
  }
}

function renderPage(param) {
  var match = React.useReducer(reducer, {
        email: "",
        password: "",
        isSubmitting: false,
        errors: {
          login: undefined,
          email: undefined,
          password: undefined
        }
      });
  var dispatch = match[1];
  var state = match[0];
  var router = Router.useRouter();
  var onLoginClick = function (param) {
    var login_email = state.email;
    var login_password = state.password;
    var login = {
      email: login_email,
      password: login_password
    };
    var errors = Common_User.Login.validateLogin(login);
    Curry._1(dispatch, {
          TAG: /* SetErrors */3,
          _0: errors
        });
    if (Common_User.Login.hasErrors(errors)) {
      return ;
    }
    Curry._1(dispatch, {
          TAG: /* SetIsSubmitting */2,
          _0: true
        });
    var onError = function (param) {
      Curry._1(dispatch, {
            TAG: /* SetErrors */3,
            _0: {
              login: "RequestFailed",
              email: undefined,
              password: undefined
            }
          });
      return Curry._1(dispatch, {
                  TAG: /* SetIsSubmitting */2,
                  _0: false
                });
    };
    var onSuccess = function (json) {
      if (Common_User.Login.hasErrors(json.errors)) {
        Curry._1(dispatch, {
              TAG: /* SetErrors */3,
              _0: json.errors
            });
        return Curry._1(dispatch, {
                    TAG: /* SetIsSubmitting */2,
                    _0: false
                  });
      }
      var nextUrl = json.nextUrl;
      if (nextUrl !== undefined) {
        router.push(nextUrl);
      } else {
        router.push(Common_Url.home(undefined));
      }
      
    };
    Client_User.login(login, onSuccess, onError);
    
  };
  var emailError = Belt_Option.map(state.errors.email, Common_User.Login.emailErrorToString);
  var passwordError = Belt_Option.map(state.errors.password, Common_User.Login.passwordErrorToString);
  return React.createElement(Page_Login_View.make, {
              email: state.email,
              emailError: emailError,
              password: state.password,
              passwordError: passwordError,
              isSubmitting: state.isSubmitting,
              loginError: state.errors.login,
              onEmailChange: (function (email) {
                  return Curry._1(dispatch, {
                              TAG: /* SetEmail */0,
                              _0: email
                            });
                }),
              onPasswordChange: (function (password) {
                  return Curry._1(dispatch, {
                              TAG: /* SetPassword */1,
                              _0: password
                            });
                }),
              onLoginClick: onLoginClick
            });
}

function $$default(param) {
  return renderPage(undefined);
}

export {
  initialState ,
  reducer ,
  renderPage ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
