// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Client_User from "../../modules/client/Client_User.mjs";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Component_Button from "../../components/Component_Button.mjs";
import * as Component_AlertMessage from "../../components/Component_AlertMessage.mjs";

function Page_Login_Resend(Props) {
  var email = Props.email;
  var match = React.useState(function () {
        return /* ResendIdle */0;
      });
  var setState = match[1];
  var state = match[0];
  var buttonState = state === 1 ? "Processing" : "Ready";
  var message;
  if (typeof state === "number") {
    switch (state) {
      case /* ResendIdle */0 :
          message = "";
          break;
      case /* ResendIsResending */1 :
          message = "Resending activation email ...";
          break;
      case /* ResendSuccess */2 :
          message = "Activation email was sent successfully.";
          break;
      
    }
  } else {
    message = Common_User.ResendActivation.errorsToString(state._0);
  }
  return React.createElement(Component_AlertMessage.make, {
              type_: "Info",
              children: null
            }, React.createElement("p", {
                  className: "mb-4"
                }, "Your account has not been activated."), React.createElement("p", {
                  className: "mb-4"
                }, React.createElement(Component_Button.Button.make, {
                      state: buttonState,
                      onClick: (function (param) {
                          Curry._1(setState, (function (param) {
                                  return /* ResendIsResending */1;
                                }));
                          var onSuccess = function (json) {
                            var errors = json.errors;
                            if (Common_User.ResendActivation.hasErrors(errors)) {
                              return Curry._1(setState, (function (param) {
                                            return /* ResendError */{
                                                    _0: errors
                                                  };
                                          }));
                            } else {
                              return Curry._1(setState, (function (param) {
                                            return /* ResendSuccess */2;
                                          }));
                            }
                          };
                          var onError = function (param) {
                            return Curry._1(setState, (function (param) {
                                          return /* ResendError */{
                                                  _0: {
                                                    resendActivation: "RequestFailed"
                                                  }
                                                };
                                        }));
                          };
                          var resendActivation = {
                            email: email
                          };
                          var errors = Common_User.ResendActivation.validateResendActivation(resendActivation);
                          if (Common_User.ResendActivation.hasErrors(errors)) {
                            return Curry._1(setState, (function (param) {
                                          return /* ResendError */{
                                                  _0: errors
                                                };
                                        }));
                          } else {
                            Client_User.resendActivationEmail(resendActivation, onSuccess, onError);
                            return ;
                          }
                        }),
                      color: "Blue",
                      size: "Small",
                      children: "Resend activation email?"
                    })), React.createElement("p", undefined, message));
}

var AlertMessage;

var make = Page_Login_Resend;

export {
  AlertMessage ,
  make ,
  
}
/* react Not a pure module */
