// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Page from "../../modules/server/Server_Page.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function getServerSideProps(context) {
  var req = context.req;
  return Server_Middleware.runAll(req, context.res).then(function (param) {
              return Server_Page.withNotAuthenticated(req, (function (param) {
                            return Promise.resolve(Server_Page.noProps(undefined));
                          }));
            });
}

export {
  getServerSideProps ,
  
}
/* Server_Page Not a pure module */
