// Generated by ReScript, PLEASE EDIT WITH CARE


function getJson(url) {
  return fetch(url).then(function (prim) {
              return prim.json();
            });
}

export {
  getJson ,
  
}
/* No side effect */
