// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LoadScript from "../../js/load-script";
import LoadScript$1 from "../../js/load-script";

var loadScript = LoadScript$1;

var removeScript = LoadScript.removeScript;

export {
  loadScript ,
  removeScript ,
  
}
/* loadScript Not a pure module */
