// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client_Xhr from "./Client_Xhr.mjs";

function signup(signup$1, onSuccess, onError) {
  return Client_Xhr.post("/api/signup", {
              TAG: /* Json */0,
              _0: signup$1
            }, onSuccess, onError, undefined);
}

export {
  signup ,
  
}
/* No side effect */
