// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Page from "../../modules/server/Server_Page.mjs";
import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(currentUser) {
  var userDto = Server_User.toCommonUserDto(currentUser);
  var props = {
    userDto: userDto
  };
  return {
          props: props,
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(context) {
  var req = context.req;
  return Server_Middleware.runAll(req, context.res).then(function (param) {
              return Server_Page.withAuthentication(req, (function (currentUser) {
                            return Promise.resolve(makeResult(currentUser));
                          }));
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* Server_Page Not a pure module */
