// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Page_Logout_View from "./Page_Logout_View.mjs";

function $$default(param) {
  return React.createElement(Page_Logout_View.make, {});
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
