// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Client_User from "../../modules/client/Client_User.mjs";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Router from "next/router";
import * as Page_ForgotPassword_View from "./Page_ForgotPassword_View.mjs";

function initialState(param) {
  return {
          email: "",
          isSubmitting: false,
          errors: {
            forgotPassword: undefined,
            email: undefined
          }
        };
}

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* SetEmail */0 :
        return {
                email: action._0,
                isSubmitting: state.isSubmitting,
                errors: state.errors
              };
    case /* SetIsSubmitting */1 :
        return {
                email: state.email,
                isSubmitting: action._0,
                errors: state.errors
              };
    case /* SetErrors */2 :
        return {
                email: state.email,
                isSubmitting: state.isSubmitting,
                errors: action._0
              };
    
  }
}

function renderPage(user) {
  var match = React.useReducer(reducer, {
        email: "",
        isSubmitting: false,
        errors: {
          forgotPassword: undefined,
          email: undefined
        }
      });
  var dispatch = match[1];
  var state = match[0];
  var router = Router.useRouter();
  var onForgotPasswordClick = function (param) {
    var forgotPassword = {
      email: state.email
    };
    var forgotPasswordErrors = Common_User.ForgotPassword.validateForgotPassword(forgotPassword);
    Curry._1(dispatch, {
          TAG: /* SetErrors */2,
          _0: forgotPasswordErrors
        });
    if (Common_User.ForgotPassword.hasErrors(forgotPasswordErrors)) {
      return ;
    }
    Curry._1(dispatch, {
          TAG: /* SetIsSubmitting */1,
          _0: true
        });
    var onError = function (param) {
      Curry._1(dispatch, {
            TAG: /* SetErrors */2,
            _0: {
              forgotPassword: "RequestFailed",
              email: undefined
            }
          });
      return Curry._1(dispatch, {
                  TAG: /* SetIsSubmitting */1,
                  _0: false
                });
    };
    var onSuccess = function (json) {
      var errors = json.errors;
      if (Common_User.ForgotPassword.hasErrors(errors)) {
        Curry._1(dispatch, {
              TAG: /* SetErrors */2,
              _0: errors
            });
        return Curry._1(dispatch, {
                    TAG: /* SetIsSubmitting */1,
                    _0: false
                  });
      } else {
        router.push(Common_Url.forgotPasswordSuccess(undefined));
        return ;
      }
    };
    Client_User.forgotPassword(forgotPassword, onSuccess, onError);
    
  };
  var forgotPasswordError = Belt_Option.map(state.errors.forgotPassword, Common_User.ForgotPassword.forgotPasswordErrorToString);
  var emailError = Belt_Option.map(state.errors.email, Common_User.ForgotPassword.emailErrorToString);
  return React.createElement(Page_ForgotPassword_View.make, {
              user: user,
              forgotPasswordError: forgotPasswordError,
              email: state.email,
              emailError: emailError,
              isSubmitting: state.isSubmitting,
              onEmailChange: (function (email) {
                  return Curry._1(dispatch, {
                              TAG: /* SetEmail */0,
                              _0: email
                            });
                }),
              onForgotPasswordClick: onForgotPasswordClick
            });
}

function $$default(param) {
  return renderPage(Common_User.User.fromNullDto(param.userDto));
}

export {
  initialState ,
  reducer ,
  renderPage ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
