// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MongoDb from "../../bindings/MongoDb.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(userDto, emailChangeSuccessful) {
  var props = {
    userDto: userDto,
    emailChangeSuccessful: emailChangeSuccessful
  };
  return {
          props: props,
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(context) {
  var params = context.params;
  var emailChangeKey = params.emailChangeKey;
  var req = context.req;
  var userId = MongoDb.ObjectId.fromString(params.userId);
  if (userId.TAG === /* Ok */0) {
    var userId$1 = userId._0;
    return Server_Middleware.run(Server_Middleware.all(undefined), req, context.res).then(function (param) {
                var match = Server_Middleware.getRequestData(req);
                var commonUser = Belt_Option.map(match.currentUser, Server_User.toCommonUserDto);
                var currentUserDto = commonUser !== undefined ? commonUser : null;
                return Server_User.changeEmailConfirm(match.client, userId$1, emailChangeKey).then(function (result) {
                            if (result.TAG === /* Ok */0) {
                              return Promise.resolve(makeResult(currentUserDto, true));
                            }
                            var props_userDto = null;
                            var props = {
                              userDto: props_userDto,
                              emailChangeSuccessful: false
                            };
                            return Promise.resolve({
                                        props: props,
                                        redirect: undefined,
                                        notFound: undefined
                                      });
                          });
              });
  }
  var props_userDto = null;
  var props = {
    userDto: props_userDto,
    emailChangeSuccessful: false
  };
  return Promise.resolve({
              props: props,
              redirect: undefined,
              notFound: undefined
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* MongoDb Not a pure module */
