// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import * as Layout_Main from "../../layouts/Layout_Main.mjs";
import * as Component_Link from "../../components/Component_Link.mjs";
import * as Component_Title from "../../components/Component_Title.mjs";

function Page_ChangeEmailConfirm_View(Props) {
  var user = Props.user;
  var emailChangeSuccessful = Props.emailChangeSuccessful;
  return React.createElement(Layout_Main.make, {
              user: user,
              children: emailChangeSuccessful ? React.createElement("div", undefined, React.createElement(Component_Title.make, {
                          text: "Email change successful",
                          size: "Primary"
                        }), React.createElement("p", {
                          className: "mb-4"
                        }, "Your email has been changed."), React.createElement("p", {
                          className: "mb-4"
                        }, React.createElement(Component_Link.make, {
                              href: Common_Url.home(undefined),
                              children: "Return to home"
                            }))) : React.createElement("div", undefined, React.createElement(Component_Title.make, {
                          text: "Email change failed",
                          size: "Primary"
                        }), React.createElement("p", {
                          className: "mb-4"
                        }, "Sorry, there was a problem confirming your email change."), React.createElement("p", {
                          className: "mb-4"
                        }, React.createElement(Component_Link.make, {
                              href: Common_Url.contact(undefined),
                              children: "Please contact us for support"
                            })))
            });
}

var Title;

var Link;

var make = Page_ChangeEmailConfirm_View;

export {
  Title ,
  Link ,
  make ,
  
}
/* react Not a pure module */
