// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import $$Error from "next/error";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Page_ChangeEmailConfirm_View from "./Page_ChangeEmailConfirm_View.mjs";

function $$default(param) {
  var user = Common_User.User.fromNullDto(param.userDto);
  if (user !== undefined) {
    return React.createElement(Page_ChangeEmailConfirm_View.make, {
                user: user,
                emailChangeSuccessful: param.emailChangeSuccessful
              });
  } else {
    return React.createElement($$Error, {
                statusCode: 403
              });
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
