// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Page from "../../modules/server/Server_Page.mjs";
import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(userDto, emailChangeSuccessful) {
  return Server_Page.props({
              userDto: userDto,
              emailChangeSuccessful: emailChangeSuccessful
            });
}

function getServerSideProps(context) {
  var params = context.params;
  var emailChangeKey = params.emailChangeKey;
  var userId = params.userId;
  var req = context.req;
  return Server_Middleware.runAll(req, context.res).then(function (param) {
              var match = Server_Middleware.getRequestData(req);
              var currentUserDto = Server_User.toNullCommonUserDto(match.currentUser);
              return Server_User.changeEmailConfirm(match.client, userId, emailChangeKey).then(function (result) {
                          if (result.TAG === /* Ok */0) {
                            return Server_Page.props({
                                        userDto: currentUserDto,
                                        emailChangeSuccessful: true
                                      });
                          } else {
                            return Server_Page.props({
                                        userDto: null,
                                        emailChangeSuccessful: false
                                      });
                          }
                        });
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* Server_Page Not a pure module */
