// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(userDto, emailChangeSuccessful) {
  var props = {
    userDto: userDto,
    emailChangeSuccessful: emailChangeSuccessful
  };
  return {
          props: props,
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(context) {
  var params = context.params;
  var emailChangeKey = params.emailChangeKey;
  var userId = params.userId;
  var req = context.req;
  return Server_Middleware.runAll(req, context.res).then(function (param) {
              var match = Server_Middleware.getRequestData(req);
              var currentUserDto = Server_User.toNullCommonUserDto(match.currentUser);
              return Server_User.changeEmailConfirm(match.client, userId, emailChangeKey).then(function (result) {
                          if (result.TAG === /* Ok */0) {
                            return makeResult(currentUserDto, true);
                          }
                          var props_userDto = null;
                          var props = {
                            userDto: props_userDto,
                            emailChangeSuccessful: false
                          };
                          return {
                                  props: props,
                                  redirect: undefined,
                                  notFound: undefined
                                };
                        });
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* Server_User Not a pure module */
