// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Page_SignupSuccess_View from "./Page_SignupSuccess_View.mjs";

function $$default(param) {
  return React.createElement(Page_SignupSuccess_View.make, {});
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
