// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Element = {};

var $$Image = {};

var $$File = {};

var $$FileList = {};

var $$FileReader = {};

function currentTarget(prim) {
  return prim.currentTarget;
}

function currentTargetFiles($$event) {
  return $$event.currentTarget.files;
}

var $$Event = {
  currentTarget: currentTarget,
  currentTargetFiles: currentTargetFiles
};

var $$FormData = {};

export {
  $$Element ,
  $$Image ,
  $$File ,
  $$FileList ,
  $$FileReader ,
  $$Event ,
  $$FormData ,
  
}
/* No side effect */
