// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Mongodb from "mongodb";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function fromString(value) {
  try {
    return {
            TAG: /* Ok */0,
            _0: Mongodb.ObjectId.createFromHexString(value)
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: /* Error */1,
              _0: "Unknown"
            };
    }
    var reason = obj._1.message;
    if (reason !== undefined) {
      return {
              TAG: /* Error */1,
              _0: reason
            };
    } else {
      return {
              TAG: /* Error */1,
              _0: "Unknown"
            };
    }
  }
}

function ObjectId_make(prim) {
  return new Mongodb.ObjectId();
}

function ObjectId_toString(prim) {
  return prim.toHexString();
}

var ObjectId = {
  make: ObjectId_make,
  toString: ObjectId_toString,
  fromString: fromString
};

var Cursor = {};

function updateOneWithSet(collection, id, update) {
  return collection.updateOne({
              _id: id
            }, {
              $set: update
            });
}

var Collection = {
  updateOneWithSet: updateOneWithSet
};

var Db = {};

var MongoClient = {};

export {
  ObjectId ,
  Cursor ,
  Collection ,
  Db ,
  MongoClient ,
  
}
/* mongodb Not a pure module */
