// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mongodb from "mongodb";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function createFromHexString(value) {
  try {
    return Caml_option.some(Mongodb.ObjectID.createFromHexString(value));
  }
  catch (exn){
    return ;
  }
}

function makeAsString(param) {
  return new Mongodb.ObjectID().toHexString();
}

var ObjectID = {
  createFromHexString: createFromHexString,
  makeAsString: makeAsString
};

var Cursor = {};

function updateOneWithSet(collection, id, update) {
  return collection.updateOne({
              _id: id
            }, {
              $set: update
            });
}

var Collection = {
  updateOneWithSet: updateOneWithSet
};

var Db = {};

var MongoClient = {};

export {
  ObjectID ,
  Cursor ,
  Collection ,
  Db ,
  MongoClient ,
  
}
/* mongodb Not a pure module */
