// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NodeFetch from "node-fetch";

function fetchJson(url, method) {
  var options = {
    method: method
  };
  return NodeFetch.fetch(url, options).then(function (prim) {
              return prim.json();
            });
}

function postJson(url) {
  return fetchJson(url, "post");
}

export {
  fetchJson ,
  postJson ,
  
}
/* node-fetch Not a pure module */
