// Generated by ReScript, PLEASE EDIT WITH CARE


function decodeReadyState(readyState) {
  if (readyState > 4 || readyState < 0) {
    return /* Unknown */5;
  } else {
    return readyState;
  }
}

function readyState(xhr) {
  return decodeReadyState(xhr.readyState);
}

export {
  decodeReadyState ,
  readyState ,
  
}
/* No side effect */
