// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Page from "../../modules/server/Server_Page.mjs";
import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(currentUser, activationSuccessful) {
  var userDto = Server_User.toNullCommonUserDto(currentUser);
  return Server_Page.props({
              userDto: userDto,
              activationSuccessful: activationSuccessful
            });
}

function getServerSideProps(context) {
  var params = context.params;
  var activationKey = params.activationKey;
  var userId = params.userId;
  var req = context.req;
  return Server_Middleware.runAll(req, context.res).then(function (param) {
              var match = Server_Middleware.getRequestData(req);
              var currentUser = match.currentUser;
              return Server_User.activate(match.client, userId, activationKey).then(function (result) {
                          if (result.TAG === /* Ok */0) {
                            return Promise.resolve(makeResult(currentUser, true));
                          } else {
                            return Promise.resolve(makeResult(currentUser, false));
                          }
                        });
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* Server_User Not a pure module */
