// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MongoDb from "../../bindings/MongoDb.mjs";
import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(activationSuccessful) {
  var props = {
    activationSuccessful: activationSuccessful
  };
  return {
          props: props,
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(context) {
  var params = context.params;
  var activationKey = params.activationKey;
  var req = context.req;
  var userId = MongoDb.ObjectId.fromString(params.userId);
  if (userId.TAG === /* Ok */0) {
    var userId$1 = userId._0;
    return Server_Middleware.run(Server_Middleware.all(undefined), req, context.res).then(function (param) {
                var match = Server_Middleware.getRequestData(req);
                return Server_User.activate(match.client, userId$1, activationKey).then(function (result) {
                            if (result.TAG === /* Ok */0) {
                              var props = {
                                activationSuccessful: true
                              };
                              return Promise.resolve({
                                          props: props,
                                          redirect: undefined,
                                          notFound: undefined
                                        });
                            }
                            var props$1 = {
                              activationSuccessful: false
                            };
                            return Promise.resolve({
                                        props: props$1,
                                        redirect: undefined,
                                        notFound: undefined
                                      });
                          });
              });
  }
  var props = {
    activationSuccessful: false
  };
  return Promise.resolve({
              props: props,
              redirect: undefined,
              notFound: undefined
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* MongoDb Not a pure module */
