// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Page_Activate_View from "./Page_Activate_View.mjs";

function $$default(param) {
  return React.createElement(Page_Activate_View.make, {
              activationSuccessful: param.activationSuccessful
            });
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
