// Generated by ReScript, PLEASE EDIT WITH CARE


function home(param) {
  return "/";
}

function contact(param) {
  return "/contact";
}

function contactSuccess(param) {
  return "/contact-success";
}

function signup(param) {
  return "/signup";
}

function signupSuccess(param) {
  return "/signup-success";
}

function login(param) {
  return "/login";
}

function logout(param) {
  return "/logout";
}

function account(param) {
  return "/account";
}

function activate(userId, activationKey) {
  return "/activate/" + userId + "/" + activationKey;
}

function resetPassword(userId, resetPasswordKey) {
  return "/reset-password/" + userId + "/" + resetPasswordKey;
}

function changeEmail(param) {
  return "/change-email";
}

function changeEmailConfirm(userId, emailChangeKey) {
  return "/change-email-confirm/" + userId + "/" + emailChangeKey;
}

function changeEmailSuccess(param) {
  return "/change-email-success";
}

function changePassword(param) {
  return "/change-password";
}

function changePasswordSuccess(param) {
  return "/change-password-success";
}

export {
  home ,
  contact ,
  contactSuccess ,
  signup ,
  signupSuccess ,
  login ,
  logout ,
  account ,
  activate ,
  resetPassword ,
  changeEmail ,
  changeEmailConfirm ,
  changeEmailSuccess ,
  changePassword ,
  changePasswordSuccess ,
  
}
/* No side effect */
