// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$String from "rescript/lib/es6/string.js";
import * as Validator from "validator";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function isValid(validation) {
  if (Belt_Option.isNone(validation.email) && Belt_Option.isNone(validation.password)) {
    return Belt_Option.isNone(validation.reCaptcha);
  } else {
    return false;
  }
}

function hasErrors(validation) {
  return !isValid(validation);
}

function validateEmail(email) {
  var emailTrimmed = $$String.trim(email);
  if (Validator.isEmpty(emailTrimmed)) {
    return "EmailEmpty";
  } else if (!Validator.isEmail(emailTrimmed)) {
    return "EmailInvalid";
  } else {
    return ;
  }
}

function validatePassword(password) {
  if (Validator.isEmpty(password)) {
    return "PasswordEmpty";
  }
  
}

function validateReCaptcha(reCaptcha) {
  if (reCaptcha !== undefined) {
    return ;
  } else {
    return "ReCaptchaEmpty";
  }
}

function validateSignup(param) {
  return {
          email: validateEmail(param.email),
          password: validatePassword(param.password),
          reCaptcha: validateReCaptcha(param.reCaptcha)
        };
}

function signupErrorToString(error) {
  return "There was a problem signing up, please try again";
}

function emailErrorToString(error) {
  if (error === "EmailEmpty") {
    return "Enter an email address";
  } else if (error === "EmailInvalid") {
    return "Enter a valid email address";
  } else {
    return "That email address is not available";
  }
}

function passwordErrorToString(error) {
  return "Enter a password";
}

function reCaptchaErrorToString(error) {
  return "Are you sure you're a robot?";
}

var Signup = {
  isValid: isValid,
  hasErrors: hasErrors,
  validateEmail: validateEmail,
  validatePassword: validatePassword,
  validateReCaptcha: validateReCaptcha,
  validateSignup: validateSignup,
  signupErrorToString: signupErrorToString,
  emailErrorToString: emailErrorToString,
  passwordErrorToString: passwordErrorToString,
  reCaptchaErrorToString: reCaptchaErrorToString
};

export {
  Signup ,
  
}
/* validator Not a pure module */
