// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Client_User from "../../modules/client/Client_User.mjs";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Router from "next/router";
import * as Common_Contact from "../../modules/common/Common_Contact.mjs";
import * as Page_Contact_View from "./Page_Contact_View.mjs";

function initialState(param) {
  return {
          name: "",
          email: "",
          message: "",
          reCaptcha: undefined,
          errors: Common_Contact.emptyErrors(undefined),
          isSubmitting: false,
          attemptCount: 0
        };
}

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            name: state.name,
            email: state.email,
            message: state.message,
            reCaptcha: state.reCaptcha,
            errors: state.errors,
            isSubmitting: state.isSubmitting,
            attemptCount: state.attemptCount + 1 | 0
          };
  }
  switch (action.TAG | 0) {
    case /* SetName */0 :
        return {
                name: action._0,
                email: state.email,
                message: state.message,
                reCaptcha: state.reCaptcha,
                errors: state.errors,
                isSubmitting: state.isSubmitting,
                attemptCount: state.attemptCount
              };
    case /* SetEmail */1 :
        return {
                name: state.name,
                email: action._0,
                message: state.message,
                reCaptcha: state.reCaptcha,
                errors: state.errors,
                isSubmitting: state.isSubmitting,
                attemptCount: state.attemptCount
              };
    case /* SetMessage */2 :
        return {
                name: state.name,
                email: state.email,
                message: action._0,
                reCaptcha: state.reCaptcha,
                errors: state.errors,
                isSubmitting: state.isSubmitting,
                attemptCount: state.attemptCount
              };
    case /* SetReCaptcha */3 :
        return {
                name: state.name,
                email: state.email,
                message: state.message,
                reCaptcha: action._0,
                errors: state.errors,
                isSubmitting: state.isSubmitting,
                attemptCount: state.attemptCount
              };
    case /* SetIsSubmitting */4 :
        return {
                name: state.name,
                email: state.email,
                message: state.message,
                reCaptcha: state.reCaptcha,
                errors: state.errors,
                isSubmitting: action._0,
                attemptCount: state.attemptCount
              };
    case /* SetErrors */5 :
        return {
                name: state.name,
                email: state.email,
                message: state.message,
                reCaptcha: state.reCaptcha,
                errors: action._0,
                isSubmitting: state.isSubmitting,
                attemptCount: state.attemptCount
              };
    
  }
}

function renderPage(user, clientConfig) {
  var match = React.useReducer(reducer, initialState(undefined));
  var dispatch = match[1];
  var state = match[0];
  var router = Router.useRouter();
  var onSendClick = function (param) {
    var contact_name = state.name;
    var contact_email = state.email;
    var contact_message = state.message;
    var contact_reCaptcha = state.reCaptcha;
    var contact = {
      name: contact_name,
      email: contact_email,
      message: contact_message,
      reCaptcha: contact_reCaptcha
    };
    var errors = Common_Contact.validateContact(contact);
    Curry._1(dispatch, {
          TAG: /* SetErrors */5,
          _0: errors
        });
    if (Common_Contact.hasErrors(errors)) {
      return ;
    }
    Curry._1(dispatch, {
          TAG: /* SetIsSubmitting */4,
          _0: true
        });
    var onError = function (param) {
      var init = Common_Contact.emptyErrors(undefined);
      var errors_contact = "RequestFailed";
      var errors_name = init.name;
      var errors_email = init.email;
      var errors_message = init.message;
      var errors_reCaptcha = init.reCaptcha;
      var errors = {
        contact: errors_contact,
        name: errors_name,
        email: errors_email,
        message: errors_message,
        reCaptcha: errors_reCaptcha
      };
      Curry._1(dispatch, {
            TAG: /* SetErrors */5,
            _0: errors
          });
      return Curry._1(dispatch, {
                  TAG: /* SetIsSubmitting */4,
                  _0: false
                });
    };
    var onSuccess = function (json) {
      var errors = json.errors;
      if (Common_Contact.hasErrors(errors)) {
        Curry._1(dispatch, {
              TAG: /* SetErrors */5,
              _0: errors
            });
        Curry._1(dispatch, {
              TAG: /* SetIsSubmitting */4,
              _0: false
            });
        return Curry._1(dispatch, /* IncrementAttemptCount */0);
      } else {
        router.push(Common_Url.contactSuccess(undefined));
        return ;
      }
    };
    Client_User.contact(contact, onSuccess, onError);
    
  };
  var contactError = Belt_Option.map(state.errors.contact, Common_Contact.contactErrorToString);
  var nameError = Belt_Option.map(state.errors.name, Common_Contact.nameErrorToString);
  var emailError = Belt_Option.map(state.errors.email, Common_Contact.emailErrorToString);
  var messageError = Belt_Option.map(state.errors.message, Common_Contact.messageErrorToString);
  var reCaptchaError = Belt_Option.map(state.errors.reCaptcha, Common_Contact.reCaptchaErrorToString);
  return React.createElement(Page_Contact_View.make, {
              reCaptchaSiteKey: clientConfig.reCaptcha.siteKey,
              user: user,
              name: state.name,
              email: state.email,
              message: state.message,
              onNameChange: (function (name) {
                  return Curry._1(dispatch, {
                              TAG: /* SetName */0,
                              _0: name
                            });
                }),
              onEmailChange: (function (email) {
                  return Curry._1(dispatch, {
                              TAG: /* SetEmail */1,
                              _0: email
                            });
                }),
              onMessageChange: (function (message) {
                  return Curry._1(dispatch, {
                              TAG: /* SetMessage */2,
                              _0: message
                            });
                }),
              onReCaptchaChange: (function (reCaptcha) {
                  return Curry._1(dispatch, {
                              TAG: /* SetReCaptcha */3,
                              _0: reCaptcha
                            });
                }),
              nameError: nameError,
              emailError: emailError,
              messageError: messageError,
              reCaptchaError: reCaptchaError,
              onSendClick: onSendClick,
              isSubmitting: state.isSubmitting,
              contactError: contactError,
              attemptCount: state.attemptCount
            });
}

function $$default(param) {
  var user = Common_User.User.fromNullDto(param.userDto);
  return renderPage(user, param.clientConfig);
}

export {
  initialState ,
  reducer ,
  renderPage ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
