// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout_Main from "../../layouts/Layout_Main.mjs";
import * as Component_Form from "../../components/Component_Form.mjs";
import * as Component_Title from "../../components/Component_Title.mjs";
import * as Component_Button from "../../components/Component_Button.mjs";
import * as Component_AlertMessage from "../../components/Component_AlertMessage.mjs";

function Page_Contact_View$ErrorMessage(Props) {
  var error = Props.error;
  if (error !== undefined) {
    return React.createElement(Component_AlertMessage.make, {
                type_: "Error",
                children: error
              });
  } else {
    return null;
  }
}

var ErrorMessage = {
  make: Page_Contact_View$ErrorMessage
};

function Page_Contact_View(Props) {
  var reCaptchaSiteKey = Props.reCaptchaSiteKey;
  var user = Props.user;
  var name = Props.name;
  var email = Props.email;
  var message = Props.message;
  var onNameChange = Props.onNameChange;
  var onEmailChange = Props.onEmailChange;
  var onMessageChange = Props.onMessageChange;
  var onReCaptchaChange = Props.onReCaptchaChange;
  var nameError = Props.nameError;
  var emailError = Props.emailError;
  var messageError = Props.messageError;
  var reCaptchaError = Props.reCaptchaError;
  var onSendClick = Props.onSendClick;
  var isSubmitting = Props.isSubmitting;
  var contactError = Props.contactError;
  var contactAttemptCount = Props.contactAttemptCount;
  return React.createElement(Layout_Main.make, {
              user: user,
              children: React.createElement(Component_Form.FormContainer.make, {
                    children: null
                  }, React.createElement(Component_Title.make, {
                        text: "Contact Us",
                        size: "Primary"
                      }), React.createElement(Page_Contact_View$ErrorMessage, {
                        error: contactError
                      }), React.createElement(Component_Form.TextField.make, {
                        label: "Your name",
                        value: name,
                        onChange: onNameChange,
                        error: nameError
                      }), React.createElement(Component_Form.TextField.make, {
                        label: "Your email",
                        value: email,
                        onChange: onEmailChange,
                        error: emailError
                      }), React.createElement(Component_Form.TextAreaField.make, {
                        label: "Your message",
                        value: message,
                        onChange: onMessageChange,
                        error: messageError
                      }), React.createElement(Component_Form.ReCaptchaField.make, {
                        reCaptchaSiteKey: reCaptchaSiteKey,
                        onChange: onReCaptchaChange,
                        error: reCaptchaError,
                        key: "recaptcha-" + String(contactAttemptCount)
                      }), React.createElement(Component_Button.Button.make, {
                        state: isSubmitting ? "Processing" : "Ready",
                        onClick: onSendClick,
                        color: "Green",
                        full: true,
                        children: "Send"
                      }))
            });
}

var Title;

var AlertMessage;

var make = Page_Contact_View;

export {
  Title ,
  AlertMessage ,
  ErrorMessage ,
  make ,
  
}
/* react Not a pure module */
