// Generated by ReScript, PLEASE EDIT WITH CARE


function makeResult(param) {
  return {
          props: {
            env: "Testing"
          },
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(_context) {
  return Promise.resolve({
              props: {
                env: "Testing"
              },
              redirect: undefined,
              notFound: undefined
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* No side effect */
