// Generated by ReScript, PLEASE EDIT WITH CARE

import Swr from "swr";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Client_Fetch from "../../modules/client/Client_Fetch.mjs";

function useCurrentUser(param) {
  var match = Swr("/api/user", Client_Fetch.getJson);
  return Caml_option.undefined_to_opt(match.data);
}

function $$default(props) {
  var envMessage = "Env is " + props.env;
  var countMessage = "Count is " + String(props.count);
  var user = useCurrentUser(undefined);
  var userMessage = user !== undefined ? "User id is " + String(user.id) : "User is not loaded";
  return React.createElement("div", undefined, envMessage, React.createElement("br", undefined), userMessage, React.createElement("br", undefined), countMessage);
}

export {
  useCurrentUser ,
  $$default ,
  $$default as default,
  
}
/* swr Not a pure module */
