// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Env from "../../modules/server/Server_Env.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Server_Test from "../../modules/server/Server_Test.mjs";
import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(stats, user) {
  var props_env = Server_Env.getString("NODE_ENV");
  var props_count = stats.count;
  var props = {
    env: props_env,
    count: props_count,
    user: user
  };
  return {
          props: props,
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(context) {
  var req = context.req;
  return Server_Middleware.run(Server_Middleware.all(undefined), req, context.res).then(function (param) {
              var match = Server_Middleware.getRequestData(req);
              var commonUser = Belt_Option.map(match.user, Server_User.toCommonUserDto);
              var commonUser$1 = commonUser !== undefined ? commonUser : null;
              return Server_Test.getStats(match.client).then(function (stats) {
                          return Promise.resolve(makeResult(stats, commonUser$1));
                        });
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* Server_Env Not a pure module */
