// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common_Url from "../common/Common_Url.mjs";

function redirect(url) {
  return {
          props: undefined,
          redirect: {
            destination: url,
            permanent: false
          },
          notFound: undefined
        };
}

function redirectHome(param) {
  return {
          props: undefined,
          redirect: {
            destination: Common_Url.home(undefined),
            permanent: false
          },
          notFound: undefined
        };
}

function redirectLogin(param) {
  return {
          props: undefined,
          redirect: {
            destination: Common_Url.login(undefined),
            permanent: false
          },
          notFound: undefined
        };
}

export {
  redirect ,
  redirectHome ,
  redirectLogin ,
  
}
/* No side effect */
