// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as MongoDb from "../../bindings/MongoDb.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function toDbUser(user) {
  var objectId = MongoDb.ObjectID.fromString(user._id);
  if (objectId.TAG !== /* Ok */0) {
    return {
            TAG: /* Error */1,
            _0: objectId._0
          };
  }
  var user__id = objectId._0;
  var user_email = user.email;
  var user_emailVerified = user.emailVerified;
  var user_password = user.password;
  var user$1 = {
    _id: user__id,
    email: user_email,
    emailVerified: user_emailVerified,
    password: user_password
  };
  return {
          TAG: /* Ok */0,
          _0: user$1
        };
}

function toCommonUser(user) {
  return {
          _id: Curry._1(MongoDb.ObjectID.toString, user._id),
          email: user.email,
          emailVerified: user.emailVerified,
          password: user.password
        };
}

function getCollection(client) {
  var db = client.db();
  return db.collection("users");
}

function getStats(client) {
  return getCollection(client).stats();
}

function insertUser(client, user) {
  var dbUser = toDbUser(user);
  return getCollection(client).insertOne(dbUser);
}

function findUserById(client, userId) {
  var userId$1 = MongoDb.ObjectID.fromString(userId);
  if (userId$1.TAG === /* Ok */0) {
    return getCollection(client).findOne({
                  _id: userId$1._0
                }).then(function (dbUser) {
                return Belt_Option.map(dbUser === undefined ? undefined : Caml_option.some(dbUser), toCommonUser);
              });
  } else {
    return Promise.resolve(undefined);
  }
}

function findUserByEmail(client, email) {
  return getCollection(client).findOne({
                email: email
              }).then(function (dbUser) {
              return Belt_Option.map(dbUser === undefined ? undefined : Caml_option.some(dbUser), toCommonUser);
            });
}

function updateUserPassword(client, userId, password) {
  var userId$1 = MongoDb.ObjectID.fromString(userId);
  if (userId$1.TAG === /* Ok */0) {
    return MongoDb.Collection.updateOneWithSet(getCollection(client), userId$1._0, {
                password: password
              });
  } else {
    return Js_exn.raiseError(userId$1._0);
  }
}

function updateEmailVerified(client, userId, emailVerified) {
  var userId$1 = MongoDb.ObjectID.fromString(userId);
  if (userId$1.TAG === /* Ok */0) {
    return MongoDb.Collection.updateOneWithSet(getCollection(client), userId$1._0, {
                emailVerified: emailVerified
              });
  } else {
    return Js_exn.raiseError(userId$1._0);
  }
}

export {
  toDbUser ,
  toCommonUser ,
  getCollection ,
  getStats ,
  insertUser ,
  findUserById ,
  findUserByEmail ,
  updateUserPassword ,
  updateEmailVerified ,
  
}
/* MongoDb Not a pure module */
