// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mongodb from "mongodb";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Server_NodeCache from "./Server_NodeCache.mjs";

function getCollection(client, name) {
  var db = client.db();
  return db.collection(name);
}

function create(client) {
  var promises = [getCollection(client, "users").createIndex({
          email: 1
        }, {
          unique: true
        })];
  return Promise.all(promises).then(function (param) {
              
            });
}

var Indexes = {
  getCollection: getCollection,
  create: create
};

var key = "mongodb";

function setClientPromise(clientPromise) {
  return Server_NodeCache.set(key, Caml_option.some(clientPromise));
}

function getClientPromise(param) {
  return Server_NodeCache.get(key);
}

var Cache = {
  key: key,
  setClientPromise: setClientPromise,
  getClientPromise: getClientPromise
};

function connect(config) {
  var clientPromise = Server_NodeCache.get(key);
  if (clientPromise !== undefined) {
    return Caml_option.valFromOption(clientPromise);
  }
  var clientPromise$1 = Mongodb.MongoClient.connect(config.uri, {
        useUnifiedTopology: true,
        useNewUrlParser: true
      });
  Server_NodeCache.set(key, Caml_option.some(clientPromise$1));
  return clientPromise$1.then(create).then(function (param) {
              return clientPromise$1;
            });
}

export {
  Indexes ,
  Cache ,
  connect ,
  
}
/* mongodb Not a pure module */
