// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Server_Env from "./Server_Env.mjs";

function isProduction(param) {
  var match = Server_Env.getNodeEnv(undefined);
  switch (match) {
    case "production" :
        return true;
    case "development" :
    case "test" :
        return false;
    default:
      return Js_exn.raiseError("Unknown environment");
  }
}

export {
  isProduction ,
  
}
/* Server_Env Not a pure module */
