// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Common_Url from "../common/Common_Url.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Server_Session from "./Server_Session.mjs";
import * as Server_Middleware from "./Server_Middleware.mjs";

function props(props$1) {
  return {
          props: Caml_option.some(props$1),
          redirect: undefined,
          notFound: undefined
        };
}

function noProps(param) {
  return props({});
}

function redirect(url) {
  return {
          props: undefined,
          redirect: {
            destination: url,
            permanent: false
          },
          notFound: undefined
        };
}

function redirectHome(param) {
  return {
          props: undefined,
          redirect: {
            destination: Common_Url.home(undefined),
            permanent: false
          },
          notFound: undefined
        };
}

function redirectLogin(param) {
  return {
          props: undefined,
          redirect: {
            destination: Common_Url.login(undefined),
            permanent: false
          },
          notFound: undefined
        };
}

function withAuthentication(req, next) {
  var match = Server_Middleware.getRequestData(req);
  var currentUser = match.currentUser;
  if (currentUser !== undefined) {
    return Curry._1(next, currentUser);
  }
  var url = req.url;
  return Server_Session.setNextUrl(req, url).then(function (param) {
              return redirectLogin(undefined);
            });
}

function withNotAuthenticated(req, next) {
  var match = Server_Middleware.getRequestData(req);
  if (match.currentUser !== undefined) {
    return Promise.resolve(redirectHome(undefined));
  } else {
    return Curry._1(next, undefined);
  }
}

export {
  props ,
  noProps ,
  redirect ,
  redirectHome ,
  redirectLogin ,
  withAuthentication ,
  withNotAuthenticated ,
  
}
/* Server_Middleware Not a pure module */
