// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nanoid from "nanoid";

var makeShortId = Nanoid.customAlphabet("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", 8);

export {
  makeShortId ,
  
}
/* makeShortId Not a pure module */
