// Generated by ReScript, PLEASE EDIT WITH CARE


function getCollection(client) {
  var db = client.db();
  return db.collection("test");
}

function getStats(client) {
  return getCollection(client).stats();
}

export {
  getCollection ,
  getStats ,
  
}
/* No side effect */
