// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Email from "./Server_Email.mjs";
import * as Common_Contact from "../common/Common_Contact.mjs";
import * as Server_ReCaptcha from "./Server_ReCaptcha.mjs";

function validateReCaptchaToken(token) {
  if (token !== undefined) {
    return Server_ReCaptcha.verifyToken(token).then(function (result) {
                if (result.TAG === /* Ok */0) {
                  return Promise.resolve(undefined);
                } else {
                  return Promise.resolve("ReCaptchaInvalid");
                }
              });
  } else {
    return Promise.resolve("ReCaptchaEmpty");
  }
}

function contact(contact$1) {
  var errors = Common_Contact.validateContact(contact$1);
  if (Common_Contact.hasErrors(errors)) {
    return Promise.resolve({
                TAG: /* Error */1,
                _0: errors
              });
  } else {
    return validateReCaptchaToken(contact$1.reCaptcha).then(function (reCaptchaError) {
                var init = Common_Contact.emptyErrors(undefined);
                var errors_contact = init.contact;
                var errors_name = init.name;
                var errors_email = init.email;
                var errors_message = init.message;
                var errors = {
                  contact: errors_contact,
                  name: errors_name,
                  email: errors_email,
                  message: errors_message,
                  reCaptcha: reCaptchaError
                };
                if (Common_Contact.hasErrors(errors)) {
                  return Promise.resolve({
                              TAG: /* Error */1,
                              _0: errors
                            });
                } else {
                  return Server_Email.sendContactEmail(contact$1).then(function (param) {
                              return Promise.resolve({
                                          TAG: /* Ok */0,
                                          _0: undefined
                                        });
                            });
                }
              });
  }
}

export {
  validateReCaptchaToken ,
  contact ,
  
}
/* Server_Email Not a pure module */
