// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Env from "./Server_Env.mjs";

function get(param) {
  var mongoDb = {
    uri: Server_Env.getString("MONGODB_URI")
  };
  return {
          mongoDb: mongoDb
        };
}

export {
  get ,
  
}
/* Server_Env Not a pure module */
