// Generated by ReScript, PLEASE EDIT WITH CARE


function set(name, value) {
  global[name] = value;
  
}

function get(name) {
  return global[name];
}

export {
  set ,
  get ,
  
}
/* No side effect */
