// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as NextIronSession from "../../bindings/NextIronSession.mjs";

function getString(prim0, prim1) {
  return prim0.session.get(prim1);
}

function destroy(prim) {
  prim.session.destroy();
  
}

function setString(req, key, value) {
  req.session.set(key, value);
  return req.session.save();
}

function unset(req, key) {
  req.session.unset(key);
  return req.session.save();
}

function setUserId(req, userId) {
  if (userId !== undefined) {
    return setString(req, "userId", userId);
  } else {
    return unset(req, "userId");
  }
}

function getUserId(req) {
  return Caml_option.nullable_to_opt(req.session.get("userId"));
}

function setNextUrl(req, nextUrl) {
  if (nextUrl !== undefined) {
    return setString(req, "nextUrl", nextUrl);
  } else {
    return unset(req, "nextUrl");
  }
}

function getNextUrl(req) {
  return Caml_option.nullable_to_opt(req.session.get("nextUrl"));
}

var getSession = NextIronSession.getSession;

export {
  getSession ,
  getString ,
  destroy ,
  setString ,
  unset ,
  setUserId ,
  getUserId ,
  setNextUrl ,
  getNextUrl ,
  
}
/* No side effect */
