// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Server_Middleware from "./Server_Middleware.mjs";

function sendJson(res, code, payload) {
  res.statusCode = (function () {
        switch (code) {
          case "Success" :
              return 200;
          case "BadRequest" :
              return 400;
          case "Forbidden" :
              return 403;
          case "NotFound" :
              return 404;
          case "ServerError" :
              return 500;
          
        }
      })();
  res.send(payload);
  
}

function sendError(res, code, error) {
  var payload = {
    error: error
  };
  return sendJson(res, code, payload);
}

function sendSuccess(res, payload) {
  return sendJson(res, "Success", payload);
}

function withBody(req, res, next) {
  var body = Server_Middleware.NextRequest.getBody(req);
  if (body !== undefined) {
    return Curry._1(next, Caml_option.valFromOption(body));
  } else {
    sendError(res, "BadRequest", "Body is missing from request");
    return Promise.resolve(undefined);
  }
}

function withCurrentUser(req, res, next) {
  var match = Server_Middleware.getRequestData(req);
  var currentUser = match.currentUser;
  if (currentUser !== undefined) {
    return Curry._1(next, currentUser);
  } else {
    sendError(res, "Forbidden", "Not logged in");
    return Promise.resolve(undefined);
  }
}

export {
  sendJson ,
  sendError ,
  sendSuccess ,
  withBody ,
  withCurrentUser ,
  
}
/* Server_Middleware Not a pure module */
