// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mongodb from "mongodb";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Server_NodeCache from "./Server_NodeCache.mjs";

var key = "mongodb";

function setClientPromise(clientPromise) {
  return Server_NodeCache.set(key, Caml_option.some(clientPromise));
}

function getClientPromise(param) {
  return Server_NodeCache.get(key);
}

var Cache = {
  key: key,
  setClientPromise: setClientPromise,
  getClientPromise: getClientPromise
};

function connect(config) {
  var clientPromise = Server_NodeCache.get(key);
  if (clientPromise !== undefined) {
    return Caml_option.valFromOption(clientPromise);
  }
  var clientPromise$1 = Mongodb.MongoClient.connect(config.uri, {
        useUnifiedTopology: true,
        useNewUrlParser: true
      });
  Server_NodeCache.set(key, Caml_option.some(clientPromise$1));
  return clientPromise$1;
}

export {
  Cache ,
  connect ,
  
}
/* mongodb Not a pure module */
