// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Server_Request_Js from "./Server_Request_Js";

function getUnsafe(prim0, prim1) {
  return Server_Request_Js.get(prim0, prim1);
}

function getData(req) {
  return Caml_option.nullable_to_opt(Server_Request_Js.getData(req));
}

function get(req, key) {
  return Caml_option.nullable_to_opt(Server_Request_Js.get(req, key));
}

function set(req, key, value) {
  Server_Request_Js.set(req, key, value);
  
}

export {
  getData ,
  get ,
  getUnsafe ,
  set ,
  
}
/* ./Server_Request_Js Not a pure module */
