// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";

function makeResult(currentUser) {
  var userDto = Server_User.toNullCommonUserDto(currentUser);
  var props = {
    userDto: userDto
  };
  return {
          props: props,
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(context) {
  var req = context.req;
  return Server_Middleware.runAll(req, context.res).then(function (param) {
              var match = Server_Middleware.getRequestData(req);
              return makeResult(match.currentUser);
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* Server_User Not a pure module */
