// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import $$Error from "next/error";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Client_User from "../../modules/client/Client_User.mjs";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Page_ChangePassword_View from "./Page_ChangePassword_View.mjs";

function initialState(param) {
  return {
          currentPassword: "",
          newPassword: "",
          newPasswordConfirm: "",
          isSubmitting: false,
          validation: {
            changePassword: undefined,
            currentPassword: undefined,
            newPassword: undefined,
            newPasswordConfirm: undefined
          },
          requestError: undefined
        };
}

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* SetCurrentPassword */0 :
        return {
                currentPassword: action._0,
                newPassword: state.newPassword,
                newPasswordConfirm: state.newPasswordConfirm,
                isSubmitting: state.isSubmitting,
                validation: state.validation,
                requestError: state.requestError
              };
    case /* SetNewPassword */1 :
        return {
                currentPassword: state.currentPassword,
                newPassword: action._0,
                newPasswordConfirm: state.newPasswordConfirm,
                isSubmitting: state.isSubmitting,
                validation: state.validation,
                requestError: state.requestError
              };
    case /* SetNewPasswordConfirm */2 :
        return {
                currentPassword: state.currentPassword,
                newPassword: state.newPassword,
                newPasswordConfirm: action._0,
                isSubmitting: state.isSubmitting,
                validation: state.validation,
                requestError: state.requestError
              };
    case /* SetIsSubmitting */3 :
        return {
                currentPassword: state.currentPassword,
                newPassword: state.newPassword,
                newPasswordConfirm: state.newPasswordConfirm,
                isSubmitting: action._0,
                validation: state.validation,
                requestError: state.requestError
              };
    case /* SetRequestError */4 :
        return {
                currentPassword: state.currentPassword,
                newPassword: state.newPassword,
                newPasswordConfirm: state.newPasswordConfirm,
                isSubmitting: state.isSubmitting,
                validation: state.validation,
                requestError: action._0
              };
    case /* SetValidation */5 :
        return {
                currentPassword: state.currentPassword,
                newPassword: state.newPassword,
                newPasswordConfirm: state.newPasswordConfirm,
                isSubmitting: state.isSubmitting,
                validation: action._0,
                requestError: state.requestError
              };
    
  }
}

function renderPage(user) {
  var match = React.useReducer(reducer, {
        currentPassword: "",
        newPassword: "",
        newPasswordConfirm: "",
        isSubmitting: false,
        validation: {
          changePassword: undefined,
          currentPassword: undefined,
          newPassword: undefined,
          newPasswordConfirm: undefined
        },
        requestError: undefined
      });
  var dispatch = match[1];
  var state = match[0];
  var onChangePasswordClick = function (param) {
    var changePassword_currentPassword = state.currentPassword;
    var changePassword_newPassword = state.newPassword;
    var changePassword_newPasswordConfirm = state.newPasswordConfirm;
    var changePassword = {
      currentPassword: changePassword_currentPassword,
      newPassword: changePassword_newPassword,
      newPasswordConfirm: changePassword_newPasswordConfirm
    };
    var changePasswordValidation = Common_User.ChangePassword.validateChangePassword(changePassword);
    Curry._1(dispatch, {
          TAG: /* SetRequestError */4,
          _0: undefined
        });
    Curry._1(dispatch, {
          TAG: /* SetValidation */5,
          _0: changePasswordValidation
        });
    if (Common_User.ChangePassword.hasErrors(changePasswordValidation)) {
      return ;
    }
    Curry._1(dispatch, {
          TAG: /* SetIsSubmitting */3,
          _0: true
        });
    var onError = function (param) {
      Curry._1(dispatch, {
            TAG: /* SetRequestError */4,
            _0: "RequestFailed"
          });
      return Curry._1(dispatch, {
                  TAG: /* SetIsSubmitting */3,
                  _0: false
                });
    };
    var onSuccess = function (json) {
      var match = json.result;
      if (match === "Error") {
        Curry._1(dispatch, {
              TAG: /* SetValidation */5,
              _0: json.validation
            });
        return Curry._1(dispatch, {
                    TAG: /* SetIsSubmitting */3,
                    _0: false
                  });
      } else {
        document.location.assign(Common_Url.changePasswordSuccess(undefined));
        return ;
      }
    };
    Client_User.changePassword(changePassword, onSuccess, onError);
    
  };
  var requestError = state.requestError;
  var requestError$1 = requestError !== undefined ? "An error occurred when trying to change your password. Please try again." : Belt_Option.map(state.validation.changePassword, Common_User.ChangePassword.changePasswordValidationErrorToString);
  var currentPasswordError = Belt_Option.map(state.validation.currentPassword, Common_User.ChangePassword.currentPasswordValidationErrorToString);
  var newPasswordError = Belt_Option.map(state.validation.newPassword, Common_User.ChangePassword.newPasswordValidationErrorToString);
  var newPasswordConfirmError = Belt_Option.map(state.validation.newPasswordConfirm, Common_User.ChangePassword.newPasswordConfirmValidationErrorToString);
  return React.createElement(Page_ChangePassword_View.make, {
              user: user,
              currentPassword: state.currentPassword,
              newPassword: state.newPassword,
              newPasswordConfirm: state.newPasswordConfirm,
              currentPasswordError: currentPasswordError,
              newPasswordError: newPasswordError,
              newPasswordConfirmError: newPasswordConfirmError,
              onCurrentPasswordChange: (function (currentPassword) {
                  return Curry._1(dispatch, {
                              TAG: /* SetCurrentPassword */0,
                              _0: currentPassword
                            });
                }),
              onNewPasswordChange: (function (newPassword) {
                  return Curry._1(dispatch, {
                              TAG: /* SetNewPassword */1,
                              _0: newPassword
                            });
                }),
              onNewPasswordConfirmChange: (function (newPasswordConfirm) {
                  return Curry._1(dispatch, {
                              TAG: /* SetNewPasswordConfirm */2,
                              _0: newPasswordConfirm
                            });
                }),
              onChangePasswordClick: onChangePasswordClick,
              requestError: requestError$1,
              isSubmitting: state.isSubmitting
            });
}

function $$default(param) {
  var user = Belt_Option.map(Caml_option.null_to_opt(param.user), Common_User.User.fromDto);
  if (user !== undefined) {
    return renderPage(user);
  } else {
    return React.createElement($$Error, {
                statusCode: 403
              });
  }
}

export {
  initialState ,
  reducer ,
  renderPage ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
