// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as Common_User from "../modules/common/Common_User.mjs";
import * as Server_User from "../modules/server/Server_User.mjs";
import * as NextConnect from "next-connect";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function handlePost(req, res) {
  var body = Server_Middleware.NextRequest.getBody(req);
  if (body !== undefined) {
    var error = Common_User.ResendActivation.validateResendActivation(body);
    if (Common_User.ResendActivation.isError(error)) {
      var result = {
        error: error
      };
      Server_Api.sendJson(res, "Success", result);
      return Promise.resolve(undefined);
    }
    var match = Server_Middleware.getRequestData(req);
    return Server_User.resendActivationEmail(match.client, body).then(function (result) {
                var result$1;
                result$1 = result.TAG === /* Ok */0 ? ({
                      error: undefined
                    }) : ({
                      error: result._0
                    });
                Server_Api.sendJson(res, "Success", result$1);
                return Promise.resolve(undefined);
              });
  }
  Server_Api.sendError(res, "ServerError", "Body is missing from request");
  return Promise.resolve(undefined);
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
