// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as Server_User from "../modules/server/Server_User.mjs";
import * as NextConnect from "next-connect";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function makePayload(forgotPasswordResult) {
  if (forgotPasswordResult.TAG === /* Ok */0) {
    return {
            result: "Ok",
            errors: undefined
          };
  }
  var errors_forgotPassword = forgotPasswordResult._0;
  var errors = {
    forgotPassword: errors_forgotPassword,
    email: undefined
  };
  return {
          result: "Error",
          errors: errors
        };
}

function handlePost(req, res) {
  return Server_Api.withBody(req, res, (function (body) {
                var match = Server_Middleware.getRequestData(req);
                return Server_User.forgotPassword(match.client, body).then(function (forgotPasswordResult) {
                            var payload = makePayload(forgotPasswordResult);
                            Server_Api.sendSuccess(res, payload);
                            return Promise.resolve(undefined);
                          });
              }));
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  makePayload ,
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
