// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as Common_User from "../modules/common/Common_User.mjs";
import * as Server_User from "../modules/server/Server_User.mjs";
import * as NextConnect from "next-connect";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function handleError(res, error) {
  var payload = {
    error: error
  };
  Server_Api.sendSuccess(res, payload);
  return Promise.resolve(undefined);
}

function handleOk(req, res, resendActivation) {
  var match = Server_Middleware.getRequestData(req);
  return Server_User.resendActivationEmail(match.client, resendActivation).then(function (result) {
              var payload;
              payload = result.TAG === /* Ok */0 ? ({
                    error: undefined
                  }) : ({
                    error: result._0
                  });
              Server_Api.sendSuccess(res, payload);
              return Promise.resolve(undefined);
            });
}

function handlePost(req, res) {
  return Server_Api.withBody(req, res, (function (body) {
                var error = Common_User.ResendActivation.validateResendActivation(body);
                if (Common_User.ResendActivation.isError(error)) {
                  return handleError(res, error);
                } else {
                  return handleOk(req, res, body);
                }
              }));
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  handleError ,
  handleOk ,
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
