// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as NextConnect from "next-connect";
import * as Server_Session from "../modules/server/Server_Session.mjs";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function handlePost(req, res) {
  Server_Session.destroy(req);
  Server_Api.sendSuccess(res, {
        result: "Ok"
      });
  return Promise.resolve(undefined);
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
