// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as NextConnect from "next-connect";

function handleGet(_req, res) {
  Server_Api.sendJson(res, "Success", {
        id: 0
      });
  return Promise.resolve(undefined);
}

var $$default = NextConnect().get(handleGet);

export {
  handleGet ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
