// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as NextConnect from "next-connect";
import * as Common_Contact from "../modules/common/Common_Contact.mjs";
import * as Server_Contact from "../modules/server/Server_Contact.mjs";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function makePayload(contactResult) {
  var errors;
  errors = contactResult.TAG === /* Ok */0 ? Common_Contact.emptyErrors(undefined) : contactResult._0;
  return {
          errors: errors
        };
}

function handlePost(req, res) {
  return Server_Api.withBody(req, res, (function (body) {
                return Server_Contact.contact(body).then(function (contactResult) {
                            var payload = makePayload(contactResult);
                            Server_Api.sendSuccess(res, payload);
                            return Promise.resolve(undefined);
                          });
              }));
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  makePayload ,
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
