// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as NextConnect from "next-connect";
import * as Server_Contact from "../modules/server/Server_Contact.mjs";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function handlePost(req, res) {
  var body = Server_Middleware.NextRequest.getBody(req);
  if (body !== undefined) {
    return Server_Contact.contact(body).then(function (contactResult) {
                var result;
                result = contactResult.TAG === /* Ok */0 ? ({
                      result: "Ok",
                      validation: contactResult._0
                    }) : ({
                      result: "Error",
                      validation: contactResult._0
                    });
                Server_Api.sendJson(res, "Success", result);
                return Promise.resolve(undefined);
              });
  } else {
    Server_Api.sendError(res, "ServerError", "Body is missing from request");
    return Promise.resolve(undefined);
  }
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
