// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as NextConnect from "next-connect";
import * as Server_Contact from "../modules/server/Server_Contact.mjs";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function makePayload(contactResult) {
  if (contactResult.TAG === /* Ok */0) {
    return {
            result: "Ok",
            validation: contactResult._0
          };
  } else {
    return {
            result: "Error",
            validation: contactResult._0
          };
  }
}

function handlePost(req, res) {
  return Server_Api.withBody(req, res, (function (body) {
                return Server_Contact.contact(body).then(function (contactResult) {
                            var payload = makePayload(contactResult);
                            Server_Api.sendSuccess(res, payload);
                            return Promise.resolve(undefined);
                          });
              }));
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  makePayload ,
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
