// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server_Api from "../modules/server/Server_Api.mjs";
import * as Common_User from "../modules/common/Common_User.mjs";
import * as Server_User from "../modules/server/Server_User.mjs";
import * as NextConnect from "next-connect";
import * as Server_Middleware from "../modules/server/Server_Middleware.mjs";

function makePayload(changePasswordResult) {
  var errors;
  errors = changePasswordResult.TAG === /* Ok */0 ? Common_User.ChangePassword.emptyErrors(undefined) : changePasswordResult._0;
  return {
          errors: errors
        };
}

function handlePost(req, res) {
  return Server_Api.withBody(req, res, (function (body) {
                return Server_Api.withCurrentUser(req, res, (function (currentUser) {
                              var match = Server_Middleware.getRequestData(req);
                              return Server_User.changePassword(match.client, currentUser._id, body).then(function (changePasswordResult) {
                                          var payload = makePayload(changePasswordResult);
                                          Server_Api.sendSuccess(res, payload);
                                          return Promise.resolve(undefined);
                                        });
                            }));
              }));
}

var $$default = NextConnect().use(Server_Middleware.all(undefined)).post(handlePost);

export {
  makePayload ,
  handlePost ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
