// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import $$Error from "next/error";

function Component_Error403(Props) {
  return React.createElement($$Error, {
              statusCode: 403,
              title: "You must be logged in to view this page"
            });
}

var make = Component_Error403;

export {
  make ,
  
}
/* react Not a pure module */
