// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Component_Title(Props) {
  var text = Props.text;
  var size = Props.size;
  var subtitle = Props.subtitle;
  var textClass = size === "Secondary" ? "text-2xl" : "text-3xl";
  return React.createElement("div", {
              className: "mb-5"
            }, React.createElement("h1", {
                  className: "font-bold " + textClass
                }, text), subtitle !== undefined ? React.createElement("p", {
                    className: "text-gray-500"
                  }, subtitle) : null);
}

var make = Component_Title;

export {
  make ,
  
}
/* react Not a pure module */
