// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Component_HtmlEntity(Props) {
  var code = Props.code;
  return React.createElement("span", {
              dangerouslySetInnerHTML: {
                __html: "&" + code + ";"
              }
            });
}

var make = Component_HtmlEntity;

export {
  make ,
  
}
/* react Not a pure module */
