// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Component_Icon from "./Component_Icon.mjs";
import * as Component_ButtonStyles from "./Component_ButtonStyles.mjs";

function getDisabled(state) {
  return state !== "Ready";
}

function getContent(state, children) {
  if (state === "Ready" || state === "Disabled") {
    return children;
  } else {
    return React.createElement(Component_Icon.ProgressSpin.make, {
                color: "White"
              });
  }
}

function Component_Button$Button(Props) {
  var state = Props.state;
  var onClick = Props.onClick;
  var colorOpt = Props.color;
  var sizeOpt = Props.size;
  var fullOpt = Props.full;
  var titleOpt = Props.title;
  var children = Props.children;
  var color = colorOpt !== undefined ? colorOpt : "Gray";
  var size = sizeOpt !== undefined ? sizeOpt : "Base";
  var full = fullOpt !== undefined ? fullOpt : false;
  var title = titleOpt !== undefined ? titleOpt : "";
  var className = Component_ButtonStyles.makeClassName(state, color, size, full);
  return React.createElement("button", {
              className: className,
              title: title,
              disabled: state !== "Ready",
              type: "button",
              onClick: onClick
            }, getContent(state, children));
}

var Button = {
  make: Component_Button$Button
};

function makeIcon(icon) {
  if (icon === "ChevronDown") {
    return React.createElement(Component_Icon.ChevronDown.make, {
                color: "White"
              });
  } else if (icon === "ChevronUp") {
    return React.createElement(Component_Icon.ChevronUp.make, {
                color: "White"
              });
  } else if (icon === "X") {
    return React.createElement(Component_Icon.X.make, {
                color: "White"
              });
  } else if (icon === "ChevronDoubleUp") {
    return React.createElement(Component_Icon.ChevronDoubleUp.make, {
                color: "White"
              });
  } else if (icon === "Trash") {
    return React.createElement(Component_Icon.Trash.make, {
                color: "White"
              });
  } else if (icon === "Menu") {
    return React.createElement(Component_Icon.Menu.make, {
                color: "White"
              });
  } else {
    return React.createElement(Component_Icon.ChevronDoubleDown.make, {
                color: "White"
              });
  }
}

function Component_Button$IconButton(Props) {
  var title = Props.title;
  var onClick = Props.onClick;
  var icon = Props.icon;
  var color = Props.color;
  var state = Props.state;
  return React.createElement(Component_Button$Button, {
              state: state,
              onClick: onClick,
              color: color,
              size: "Small",
              title: title,
              children: makeIcon(icon)
            });
}

var IconButton = {
  Icon: undefined,
  makeIcon: makeIcon,
  make: Component_Button$IconButton
};

var Icon;

var ButtonStyles;

export {
  Icon ,
  ButtonStyles ,
  getDisabled ,
  getContent ,
  Button ,
  IconButton ,
  
}
/* react Not a pure module */
