// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Client_Script from "../modules/client/Client_Script.mjs";

var prepare = (function init(id, siteKey, onChange) {
    var onLoadName = "reCaptchaOnLoad";
    var onDoneName = "reCaptchaOnDone";

    window[onLoadName] = function() {
      grecaptcha.render(id, {
        sitekey: siteKey,
        callback: onDoneName
      });
    };

    window[onDoneName] = onChange;

    var url = "https://www.google.com/recaptcha/api.js?onload=" + onLoadName + "&render=explicit";

    return url;
  });

var reCaptchaId = "reCaptcha";

function Component_ReCaptcha(Props) {
  var reCaptchaSiteKey = Props.reCaptchaSiteKey;
  var onChange = Props.onChange;
  var match = React.useState(function () {
        return false;
      });
  var setIsLoaded = match[1];
  var isLoaded = match[0];
  React.useEffect((function () {
          if (!isLoaded) {
            var url = prepare(reCaptchaId, reCaptchaSiteKey, onChange);
            Client_Script.loadScript(url, (function (param) {
                    
                  }), (function (param) {
                    
                  }));
            Curry._1(setIsLoaded, (function (param) {
                    return true;
                  }));
          }
          
        }), []);
  return React.createElement("div", {
              id: reCaptchaId
            });
}

var make = Component_ReCaptcha;

export {
  prepare ,
  reCaptchaId ,
  make ,
  
}
/* react Not a pure module */
