// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Component_ContentContainer(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "container mx-auto px-4"
            }, children);
}

var make = Component_ContentContainer;

export {
  make ,
  
}
/* react Not a pure module */
