// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Page_ContactSuccess_View from "./Page_ContactSuccess_View.mjs";

function $$default(param) {
  var user = Caml_option.null_to_opt(param.user);
  return React.createElement(Page_ContactSuccess_View.make, {
              user: user
            });
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
