// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(props) {
  return React.createElement("div", undefined, props.msg, React.createElement("a", {
                  href: props.href,
                  target: "_blank"
                }, "`src/Examples.res`"));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
