// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Page_Account_View from "./Page_Account_View.mjs";
import * as Component_Error403 from "../../components/Component_Error403.mjs";

function $$default(param) {
  var user = Common_User.User.fromNullDto(param.userDto);
  if (user !== undefined) {
    return React.createElement(Page_Account_View.make, {
                user: user
              });
  } else {
    return React.createElement(Component_Error403.make, {});
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
