// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import * as Layout_Main from "../../layouts/Layout_Main.mjs";
import * as Component_Link from "../../components/Component_Link.mjs";
import * as Component_Title from "../../components/Component_Title.mjs";
import * as Component_AlertMessage from "../../components/Component_AlertMessage.mjs";

function Page_Account_View$EmailChangeAlert(Props) {
  var user = Props.user;
  var email = user.emailChange;
  if (email !== undefined) {
    return React.createElement("div", {
                className: "mt-4"
              }, React.createElement(Component_AlertMessage.make, {
                    type_: "Info",
                    children: null
                  }, React.createElement("div", {
                        className: "font-bold"
                      }, "Pending email change"), React.createElement("div", {
                        className: "overflow-ellipsis overflow-hidden"
                      }, email)));
  } else {
    return null;
  }
}

var EmailChangeAlert = {
  make: Page_Account_View$EmailChangeAlert
};

function Page_Account_View(Props) {
  var user = Props.user;
  return React.createElement(Layout_Main.make, {
              user: user,
              children: null
            }, React.createElement(Component_Title.make, {
                  text: "Account",
                  size: "Primary"
                }), React.createElement("hr", {
                  className: "mb-6"
                }), React.createElement("div", {
                  className: "mb-6"
                }, React.createElement("div", {
                      className: "font-bold"
                    }, "Email"), React.createElement("div", {
                      className: "overflow-ellipsis overflow-hidden"
                    }, user.email), React.createElement(Component_Link.make, {
                      href: Common_Url.changeEmail(undefined),
                      children: "Change email"
                    }), React.createElement(Page_Account_View$EmailChangeAlert, {
                      user: user
                    })), React.createElement("hr", {
                  className: "mb-6"
                }), React.createElement("div", {
                  className: "mb-6"
                }, React.createElement("div", {
                      className: "font-bold"
                    }, "Password"), React.createElement(Component_Link.make, {
                      href: Common_Url.changePassword(undefined),
                      children: "Change password"
                    })));
}

var Title;

var AlertMessage;

var Link;

var make = Page_Account_View;

export {
  Title ,
  AlertMessage ,
  Link ,
  EmailChangeAlert ,
  make ,
  
}
/* react Not a pure module */
