// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "next/router";

var PageComponent = {};

function $$default(props) {
  Router.useRouter();
  return React.createElement(props.Component, props.pageProps);
}

var Main;

export {
  Main ,
  PageComponent ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
