// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout_Main from "../../layouts/Layout_Main.mjs";
import * as Router from "next/router";

var PageComponent = {};

function $$default(props) {
  Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  return React.createElement(Layout_Main.make, {
              children: content
            });
}

var Main;

export {
  Main ,
  PageComponent ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
