// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Common_Url from "../../modules/common/Common_Url.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Client_User from "../../modules/client/Client_User.mjs";
import * as Common_User from "../../modules/common/Common_User.mjs";
import * as Router from "next/router";
import * as Page_Signup_View from "./Page_Signup_View.mjs";

function initialState(param) {
  return {
          email: "",
          password: "",
          reCaptcha: undefined,
          isSubmitting: false,
          signupAttemptCount: 0,
          errors: {
            signup: undefined,
            email: undefined,
            password: undefined,
            reCaptcha: undefined
          }
        };
}

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            email: state.email,
            password: state.password,
            reCaptcha: state.reCaptcha,
            isSubmitting: state.isSubmitting,
            signupAttemptCount: state.signupAttemptCount + 1 | 0,
            errors: state.errors
          };
  }
  switch (action.TAG | 0) {
    case /* SetEmail */0 :
        return {
                email: action._0,
                password: state.password,
                reCaptcha: state.reCaptcha,
                isSubmitting: state.isSubmitting,
                signupAttemptCount: state.signupAttemptCount,
                errors: state.errors
              };
    case /* SetPassword */1 :
        return {
                email: state.email,
                password: action._0,
                reCaptcha: state.reCaptcha,
                isSubmitting: state.isSubmitting,
                signupAttemptCount: state.signupAttemptCount,
                errors: state.errors
              };
    case /* SetReCaptcha */2 :
        return {
                email: state.email,
                password: state.password,
                reCaptcha: action._0,
                isSubmitting: state.isSubmitting,
                signupAttemptCount: state.signupAttemptCount,
                errors: state.errors
              };
    case /* SetIsSubmitting */3 :
        return {
                email: state.email,
                password: state.password,
                reCaptcha: state.reCaptcha,
                isSubmitting: action._0,
                signupAttemptCount: state.signupAttemptCount,
                errors: state.errors
              };
    case /* SetErrors */4 :
        return {
                email: state.email,
                password: state.password,
                reCaptcha: state.reCaptcha,
                isSubmitting: state.isSubmitting,
                signupAttemptCount: state.signupAttemptCount,
                errors: action._0
              };
    
  }
}

function renderPage(clientConfig) {
  var match = React.useReducer(reducer, {
        email: "",
        password: "",
        reCaptcha: undefined,
        isSubmitting: false,
        signupAttemptCount: 0,
        errors: {
          signup: undefined,
          email: undefined,
          password: undefined,
          reCaptcha: undefined
        }
      });
  var dispatch = match[1];
  var state = match[0];
  var router = Router.useRouter();
  var onSignupClick = function (param) {
    var signup_email = state.email;
    var signup_password = state.password;
    var signup_reCaptcha = state.reCaptcha;
    var signup = {
      email: signup_email,
      password: signup_password,
      reCaptcha: signup_reCaptcha
    };
    var errors = Common_User.Signup.validateSignup(signup);
    Curry._1(dispatch, {
          TAG: /* SetErrors */4,
          _0: errors
        });
    if (Common_User.Signup.hasErrors(errors)) {
      return ;
    }
    Curry._1(dispatch, {
          TAG: /* SetIsSubmitting */3,
          _0: true
        });
    var onError = function (param) {
      Curry._1(dispatch, {
            TAG: /* SetErrors */4,
            _0: {
              signup: "RequestFailed",
              email: undefined,
              password: undefined,
              reCaptcha: undefined
            }
          });
      return Curry._1(dispatch, {
                  TAG: /* SetIsSubmitting */3,
                  _0: false
                });
    };
    var onSuccess = function (json) {
      var errors = json.errors;
      if (Common_User.Signup.hasErrors(errors)) {
        Curry._1(dispatch, {
              TAG: /* SetErrors */4,
              _0: errors
            });
        Curry._1(dispatch, {
              TAG: /* SetIsSubmitting */3,
              _0: false
            });
        return Curry._1(dispatch, /* IncrementSignupAttemptCount */0);
      } else {
        router.push(Common_Url.signupSuccess(undefined));
        return ;
      }
    };
    Client_User.signup(signup, onSuccess, onError);
    
  };
  var signupError = Belt_Option.map(state.errors.signup, Common_User.Signup.signupErrorToString);
  var emailError = Belt_Option.map(state.errors.email, Common_User.Signup.emailErrorToString);
  var passwordError = Belt_Option.map(state.errors.password, Common_User.Signup.passwordErrorToString);
  var reCaptchaError = Belt_Option.map(state.errors.reCaptcha, Common_User.Signup.reCaptchaErrorToString);
  return React.createElement(Page_Signup_View.make, {
              reCaptchaSiteKey: clientConfig.reCaptcha.siteKey,
              email: state.email,
              emailError: emailError,
              password: state.password,
              passwordError: passwordError,
              reCaptchaError: reCaptchaError,
              isSubmitting: state.isSubmitting,
              signupError: signupError,
              signupAttemptCount: state.signupAttemptCount,
              onEmailChange: (function (email) {
                  return Curry._1(dispatch, {
                              TAG: /* SetEmail */0,
                              _0: email
                            });
                }),
              onPasswordChange: (function (password) {
                  return Curry._1(dispatch, {
                              TAG: /* SetPassword */1,
                              _0: password
                            });
                }),
              onReCaptchaChange: (function (password) {
                  return Curry._1(dispatch, {
                              TAG: /* SetReCaptcha */2,
                              _0: password
                            });
                }),
              onSignupClick: onSignupClick
            });
}

function $$default(param) {
  return renderPage(param.clientConfig);
}

export {
  initialState ,
  reducer ,
  renderPage ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
