// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout_Common from "./Layout_Common.mjs";
import * as Component_ContentContainer from "../components/Component_ContentContainer.mjs";

function Layout_Main2(Props) {
  var user = Props.user;
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, React.createElement(Layout_Common.Header.make, {
                  user: user
                }), React.createElement(Component_ContentContainer.make, {
                  children: React.createElement("div", {
                        className: "mb-48"
                      }, children)
                }), React.createElement(Layout_Common.Footer.make, {}));
}

var make = Layout_Main2;

export {
  make ,
  
}
/* react Not a pure module */
