// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function Layout_Main$Navigation(Props) {
  return React.createElement("nav", {
              className: "p-2 h-12 flex border-b border-gray-200 justify-between items-center text-sm"
            }, React.createElement(Link, {
                  href: "/",
                  children: React.createElement("a", {
                        className: "flex items-center"
                      }, React.createElement("img", {
                            className: "w-5",
                            src: "/static/zeit-black-triangle.svg"
                          }), React.createElement("span", {
                            className: "text-xl ml-2 align-middle font-semibold"
                          }, "Next + MongoDB + ReScript"))
                }), React.createElement("div", {
                  className: "flex justify-end"
                }, React.createElement(Link, {
                      href: "/",
                      children: React.createElement("a", {
                            className: "px-3"
                          }, "Home")
                    }), React.createElement(Link, {
                      href: "/login",
                      children: React.createElement("a", {
                            className: "px-3"
                          }, "Login")
                    }), React.createElement(Link, {
                      href: "/signup",
                      children: React.createElement("a", {
                            className: "px-3"
                          }, "Signup")
                    })));
}

function Layout_Main(Props) {
  var children = Props.children;
  var minWidth = {
    minWidth: "20rem"
  };
  return React.createElement("div", {
              className: "flex lg:justify-center",
              style: minWidth
            }, React.createElement("div", {
                  className: "max-w-5xl w-full lg:w-3/4 text-gray-900 font-base"
                }, React.createElement(Layout_Main$Navigation, {}), React.createElement("main", {
                      className: "mt-4 mx-4"
                    }, children)));
}

var make = Layout_Main;

export {
  make ,
  
}
/* react Not a pure module */
