// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Marked from "marked";
import * as Server_User from "../../modules/server/Server_User.mjs";
import * as Server_Middleware from "../../modules/server/Server_Middleware.mjs";
import * as Page_Privacy_Markdown from "./Page_Privacy_Markdown.mjs";

function makeResult(currentUser, html) {
  var userDto = Server_User.toNullCommonUserDto(currentUser);
  var props = {
    userDto: userDto,
    html: html
  };
  return {
          props: props,
          redirect: undefined,
          notFound: undefined
        };
}

function getServerSideProps(context) {
  var req = context.req;
  return Server_Middleware.run(Server_Middleware.all(undefined), req, context.res).then(function (param) {
              var match = Server_Middleware.getRequestData(req);
              var html = Marked(Page_Privacy_Markdown.markdown);
              return Promise.resolve(makeResult(match.currentUser, html));
            });
}

export {
  makeResult ,
  getServerSideProps ,
  
}
/* marked Not a pure module */
